import assert from 'node:assert/strict';
import worker from './dist/server/index.js';
const env={ENEM_PASSWORD:'only-a-test-password'};
const origin='https://test.example';
const request=(path,options={})=>new Request(origin+path,options);
let r=await worker.fetch(request('/'),env);
assert.equal(r.status,200);assert.match(await r.text(),/Senha de acesso/);
r=await worker.fetch(request('/app.js'),env);assert.match(await r.text(),/Senha de acesso/);
const login=(password,requestOrigin=origin)=>worker.fetch(request('/login',{method:'POST',headers:{origin:requestOrigin},body:new URLSearchParams({password})}),env);
r=await login('incorrect');assert.equal(r.status,401);assert.equal(r.headers.get('set-cookie'),null);
r=await login(env.ENEM_PASSWORD,'https://elsewhere.example');assert.equal(r.status,403);
r=await login(env.ENEM_PASSWORD);assert.equal(r.status,303);
const cookie=r.headers.get('set-cookie');assert.match(cookie,/HttpOnly; Secure; SameSite=Strict/);
const session=cookie.split(';')[0];
r=await worker.fetch(request('/',{headers:{cookie:session}}),env);assert.match(await r.text(),/welcome-title/);
r=await worker.fetch(request('/app.js',{headers:{cookie:session}}),env);assert.match(r.headers.get('content-type'),/javascript/);
const altered=session.slice(0,-1)+(session.endsWith('a')?'b':'a');
r=await worker.fetch(request('/',{headers:{cookie:altered}}),env);assert.match(await r.text(),/Senha de acesso/);
r=await worker.fetch(request('/',{headers:{cookie:session}}),{ENEM_PASSWORD:'changed-test-password'});assert.match(await r.text(),/Senha de acesso/);
r=await worker.fetch(request('/'),{});assert.equal(r.status,503);
console.log('PASS: protected pages/assets, incorrect password, cross-origin login, valid login, secure cookie, tamper rejection, password rotation, missing-secret fail-closed.');
